// src/mock/mockCoursesStudent.js

export const mockCoursesStudent = [
  {
    id: "1",
    title: "Final Exam Revision",
    courseTitle: "Calculus I",
    tutorName: "Hoàng Tunilever",
    rating: "4.8",
    date: "Nov 5, 2025",
    time: "18:00 - 20:00",
    locationType: "Online (Google Meet)",
    locationLink: "https://meet.google.com/demo1",
    capacity: 40,
    registered: 30,
    status: "upcoming",
    description: "Comprehensive revision for final calculus exam.",
    learningGoals: ["Review formulas", "Solve sample exams"],
    img: "https://picsum.photos/id/1011/600/400",
  },
  {
    id: "2",
    title: "React Hook Practice",
    courseTitle: "React Web Development",
    tutorName: "Anna Smith",
    rating: "4.6",
    date: "Nov 6, 2025",
    time: "19:00 - 21:00",
    locationType: "Offline at Campus",
    locationLink: "",
    capacity: 35,
    registered: 28,
    status: "ongoing",
    description: "Hands-on React hooks practice.",
    learningGoals: ["useState", "useEffect"],
    img: "https://picsum.photos/id/1025/600/400",
  },
  {
    id: "3",
    title: "SQL Query Mastery",
    courseTitle: "Database Systems",
    tutorName: "Chris Paul",
    rating: "4.7",
    date: "Nov 7, 2025",
    time: "18:30 - 20:30",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo3",
    capacity: 45,
    registered: 40,
    status: "finished",
    description: "Advanced SQL query techniques.",
    learningGoals: ["JOIN", "GROUP BY"],
    img: "https://picsum.photos/id/1040/600/400",
  },
  {
    id: "4",
    title: "Python Loop Techniques",
    courseTitle: "Python Programming",
    tutorName: "Emily Watson",
    rating: "4.9",
    date: "Nov 8, 2025",
    time: "17:00 - 19:00",
    locationType: "Offline at Campus",
    locationLink: "",
    capacity: 40,
    registered: 22,
    status: "upcoming",
    description: "Master Python loops by real exercises.",
    learningGoals: ["for loop", "while loop"],
    img: "https://picsum.photos/id/1052/600/400",
  },
  {
    id: "5",
    title: "Machine Learning Basics",
    courseTitle: "Data Science Basics",
    tutorName: "David Nguyen",
    rating: "4.5",
    date: "Nov 9, 2025",
    time: "18:00 - 20:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo5",
    capacity: 50,
    registered: 45,
    status: "ongoing",
    description: "Introduction to machine learning models.",
    learningGoals: ["Regression", "Classification"],
    img: "https://picsum.photos/id/1060/600/400",
  },
  {
    id: "6",
    title: "Java OOP Concepts",
    courseTitle: "Object Oriented Programming",
    tutorName: "Michael Brown",
    rating: "4.6",
    date: "Nov 10, 2025",
    time: "18:30 - 20:30",
    locationType: "Offline at Campus",
    locationLink: "",
    capacity: 35,
    registered: 20,
    status: "upcoming",
    description: "Understanding OOP with Java.",
    learningGoals: ["Class", "Inheritance"],
    img: "https://picsum.photos/id/1069/600/400",
  },
  {
    id: "7",
    title: "API Development",
    courseTitle: "Backend Web",
    tutorName: "Sophia Miller",
    rating: "4.7",
    date: "Nov 11, 2025",
    time: "19:00 - 21:00",
    locationType: "Online (Google Meet)",
    locationLink: "https://meet.google.com/demo7",
    capacity: 40,
    registered: 29,
    status: "ongoing",
    description: "Build RESTful APIs.",
    learningGoals: ["REST", "Postman"],
    img: "https://picsum.photos/id/1074/600/400",
  },
  {
    id: "8",
    title: "UI Design Fundamentals",
    courseTitle: "UI/UX Design",
    tutorName: "Daniel Martinez",
    rating: "4.5",
    date: "Nov 12, 2025",
    time: "17:00 - 19:00",
    locationType: "Offline at Campus",
    capacity: 30,
    registered: 18,
    status: "finished",
    description: "Basic principles of UI design.",
    learningGoals: ["Color", "Typography"],
    img: "https://picsum.photos/id/1080/600/400",
  },
  {
    id: "9",
    title: "Cyber Security Basics",
    courseTitle: "Cyber Security",
    tutorName: "Olivia Johnson",
    rating: "4.9",
    date: "Nov 13, 2025",
    time: "18:00 - 20:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo9",
    capacity: 45,
    registered: 40,
    status: "upcoming",
    description: "Protect systems from cyber attacks.",
    learningGoals: ["Malware", "Phishing"],
    img: "https://picsum.photos/id/1084/600/400",
  },
  {
    id: "10",
    title: "Cloud Computing Intro",
    courseTitle: "Cloud Technology",
    tutorName: "James Anderson",
    rating: "4.6",
    date: "Nov 14, 2025",
    time: "19:00 - 21:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo10",
    capacity: 50,
    registered: 42,
    status: "ongoing",
    description: "Basics of cloud computing.",
    learningGoals: ["AWS", "Cloud storage"],
    img: "https://picsum.photos/id/1081/600/400",
  },

  {
    id: "11",
    title: "Data Visualization",
    courseTitle: "Data Analysis",
    tutorName: "Laura White",
    rating: "4.7",
    date: "Nov 15, 2025",
    time: "18:00 - 20:00",
    locationType: "Offline at Campus",
    capacity: 35,
    registered: 25,
    status: "finished",
    description: "Visualizing data with charts.",
    learningGoals: ["Charts", "Dashboard"],
    img: "https://picsum.photos/id/1082/600/400",
  },
  {
    id: "12",
    title: "Advanced JavaScript",
    courseTitle: "JavaScript Fullstack",
    tutorName: "Kevin Tran",
    rating: "4.8",
    date: "Nov 16, 2025",
    time: "19:00 - 21:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo12",
    capacity: 45,
    registered: 33,
    status: "ongoing",
    description: "Advanced techniques in JavaScript.",
    learningGoals: ["Async/Await", "Closures"],
    img: "https://picsum.photos/id/1083/600/400",
  },
  {
    id: "13",
    title: "Mobile App UI",
    courseTitle: "Mobile Development",
    tutorName: "Sarah Parker",
    rating: "4.5",
    date: "Nov 17, 2025",
    time: "17:30 - 19:30",
    locationType: "Offline at Campus",
    capacity: 30,
    registered: 20,
    status: "upcoming",
    description: "Design UI for mobile apps.",
    learningGoals: ["Layout", "User flow"],
    img: "https://picsum.photos/id/1087/600/400",
  },
  {
    id: "14",
    title: "Linear Regression",
    courseTitle: "Machine Learning",
    tutorName: "Brian Lee",
    rating: "4.9",
    date: "Nov 18, 2025",
    time: "18:30 - 20:30",
    locationType: "Online (Google Meet)",
    locationLink: "https://meet.google.com/demo14",
    capacity: 40,
    registered: 34,
    status: "ongoing",
    description: "Understanding linear regression.",
    learningGoals: ["Model training", "Prediction"],
    img: "https://picsum.photos/id/1090/600/400",
  },
  {
    id: "15",
    title: "Operating System Basics",
    courseTitle: "Operating Systems",
    tutorName: "Robert King",
    rating: "4.6",
    date: "Nov 19, 2025",
    time: "18:00 - 20:00",
    locationType: "Offline at Campus",
    capacity: 45,
    registered: 37,
    status: "finished",
    description: "Introduction to operating systems.",
    learningGoals: ["Process", "Thread"],
    img: "https://picsum.photos/id/1091/600/400",
  },
  {
    id: "16",
    title: "Docker for Beginners",
    courseTitle: "DevOps",
    tutorName: "Nancy Drew",
    rating: "4.7",
    date: "Nov 20, 2025",
    time: "19:00 - 21:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo16",
    capacity: 40,
    registered: 29,
    status: "upcoming",
    description: "Containerization with Docker.",
    learningGoals: ["Image", "Container"],
    img: "https://picsum.photos/id/1095/600/400",
  },
  {
    id: "17",
    title: "Network Security",
    courseTitle: "Computer Networks",
    tutorName: "Victor Hugo",
    rating: "4.8",
    date: "Nov 21, 2025",
    time: "18:30 - 20:30",
    locationType: "Offline at Campus",
    capacity: 35,
    registered: 26,
    status: "ongoing",
    description: "Secure network architecture.",
    learningGoals: ["Firewall", "Encryption"],
    img: "https://picsum.photos/id/110/600/400",
  },
  {
    id: "18",
    title: "Time Series Forecasting",
    courseTitle: "Data Science Advanced",
    tutorName: "Andrew Ng",
    rating: "4.9",
    date: "Nov 22, 2025",
    time: "19:00 - 21:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo18",
    capacity: 50,
    registered: 45,
    status: "finished",
    description: "Forecasting with time series data.",
    learningGoals: ["ARIMA", "Forecasting"],
    img: "https://picsum.photos/id/111/600/400",
  },
  {
    id: "19",
    title: "Agile Project Management",
    courseTitle: "Software Engineering",
    tutorName: "Lisa Wong",
    rating: "4.6",
    date: "Nov 23, 2025",
    time: "17:00 - 19:00",
    locationType: "Offline at Campus",
    capacity: 40,
    registered: 31,
    status: "upcoming",
    description: "Agile methodology for projects.",
    learningGoals: ["Scrum", "Sprint"],
    img: "https://picsum.photos/id/112/600/400",
  },
  {
    id: "20",
    title: "Blockchain Overview",
    courseTitle: "Blockchain Technology",
    tutorName: "Elon Tran",
    rating: "4.7",
    date: "Nov 24, 2025",
    time: "18:00 - 20:00",
    locationType: "Online (Zoom)",
    locationLink: "https://zoom.us/demo20",
    capacity: 45,
    registered: 38,
    status: "ongoing",
    description: "Introduction to blockchain systems.",
    learningGoals: ["Bitcoin", "Smart contract"],
    img: "https://picsum.photos/id/113/600/400",
  },
];
